// data.js
export const data = [
  {
    no: 1,
    activity: "sample1",
    emissionFacility: "A그룹",
    regulatoryGrade: "A그룹",
    usageGrade: "Tier 1",
    netEmissionGrade: "Tier 1",
    emissionCalcGrade: "Tier 1",
    calculationCoefficienGrade: "Tier 1",
    calcDate: "2024-02-03",
  },
  {
    no: 2,
    activity: "sample2",
    emissionFacility: "A그룹",
    regulatoryGrade: "A그룹",
    usageGrade: "Tier 1",
    netEmissionGrade: "Tier 1",
    emissionCalcGrade: "Tier 1",
    calculationCoefficienGrade: "Tier 1",
    calcDate: "2024-02-03",
  },
  {
    no: 3,
    activity: "sample3",
    emissionFacility: "A그룹",
    regulatoryGrade: "A그룹",
    usageGrade: "Tier 1",
    netEmissionGrade: "Tier 1",
    emissionCalcGrade: "Tier 1",
    calculationCoefficienGrade: "Tier 1",
    calcDate: "2024-02-03",
  },
  {
    no: 4,
    activity: "sample4",
    emissionFacility: "A그룹",
    regulatoryGrade: "A그룹",
    usageGrade: "Tier 1",
    netEmissionGrade: "Tier 1",
    emissionCalcGrade: "Tier 1",
    calculationCoefficienGrade: "Tier 1",
    calcDate: "2024-02-03",
  },
  {
    no: 5,
    activity: "sample5",
    emissionFacility: "A그룹",
    regulatoryGrade: "A그룹",
    usageGrade: "Tier 1",
    netEmissionGrade: "Tier 1",
    emissionCalcGrade: "Tier 1",
    calculationCoefficienGrade: "Tier 1",
    calcDate: "2024-02-03",
  },
];
