export const exampleData = [
  {
    id: 1,
    parameterID: "202508",
    upperGroup: "에너지사용량",
    group: "에너지사용량",
    inputType: "시스템 결과값",
    tier: "Tier 1",
    value: "0",
    version: "1.0",
    unit: "TJ",
    fuel: "프로판",
    activity: "역세권 연소",
    industry: "에너지산업",
  },
  {
    id: 2,
    parameterID: "10508",
    upperGroup: "산화계수",
    group: "산화계수",
    inputType: "시스템 결과값",
    tier: "Tier 1",
    value: "0",
    version: "1.0",
    unit: "TJ",
    fuel: "프로판",
    activity: "역세권 연소",
    industry: "에너지산업",
  },
  {
    id: 3,
    parameterID: "202308",
    upperGroup: "배출계수",
    group: "이산화탄소(co2)배출계수",
    inputType: "시스템 결과값",
    tier: "Tier 1",
    value: "0",
    version: "1.0",
    unit: "TJ",
    fuel: "프로판",
    activity: "역세권 연소",
    industry: "에너지산업",
  },
  {
    id: 4,
    parameterID: "202548",
    upperGroup: "에너지사용량",
    group: "에너지사용량",
    inputType: "시스템 결과값",
    tier: "Tier 1",
    value: "0",
    version: "1.0",
    unit: "TJ",
    fuel: "프로판",
    activity: "역세권 연소",
    industry: "에너지산업",
  },
  {
    id: 5,
    parameterID: "202318",
    upperGroup: "배출계수",
    group: "이산화탄소(co2)배출계수",
    inputType: "시스템 결과값",
    tier: "Tier 1",
    value: "0",
    version: "1.0",
    unit: "TJ",
    fuel: "프로판",
    activity: "역세권 연소",
    industry: "에너지산업",
  },
];

export default exampleData;
